import { Box } from "@mui/material";
import { DataGrid } from "@mui/x-data-grid";
import { useEffect, useState } from "react";
import { DontationReport } from "../../types/reports";
import { getDonationReport } from "../../utils/apiClient";
import { columnForDonationReport } from "../table/columnsConfig";

function ReportByType() {
  const [donationReport, setDonationReport] = useState<DontationReport[]>([]);
  useEffect(() => {
    getDonationReport()
      .then((data) => setDonationReport(data))
      .catch((error) => console.log(error));
  }, []);

  return (
    <div>
      <h1>Inventory Report: Donations by Type</h1>
      <h2>Date: {new Date().toLocaleString()}</h2>
      <h2>Generated By: user</h2>

      <Box sx={{ width: "100%" }}>
        {donationReport && (
          <DataGrid
            rows={donationReport}
            columns={columnForDonationReport}
            getRowId={(row) => row.donationType}
            autoHeight
            disableRowSelectionOnClick
          />
        )}
      </Box>
    </div>
  );
}

export default ReportByType;
