import Box from "@mui/material/Box/Box";
import { DataGrid } from "@mui/x-data-grid/DataGrid/DataGrid";
import { useEffect, useState } from "react";
import { DonorReport } from "../../types/reports";
import { getDonorReport } from "../../utils/apiClient";
import { columnForDonorReport } from "../table/columnsConfig";

function ReportByDonor() {
  const [donorReport, setDonorReport] = useState<DonorReport[]>([]);

  useEffect(() => {
    getDonorReport()
      .then((data) => setDonorReport(data))
      .catch((error) => console.log(error));
  }, []);

  return (
    <div>
      <h1>Donor Report: Donations by Donor</h1>
      <h2>Date: {new Date().toLocaleString()}</h2>
      <h2>Generated By: user</h2>

      <Box sx={{ width: "100%" }}>
        {donorReport && (
          <DataGrid
            rows={donorReport}
            columns={columnForDonorReport}
            getRowId={(row) => row.donorName}
            autoHeight
            disableRowSelectionOnClick
          />
        )}
      </Box>
    </div>
  );
}

export default ReportByDonor;
